#!/bin/sh

NUM=5

while getopts ":mrn:" opt; do
    case $opt in
        m) FORMAT="markus" ;;
        r) FORMAT="ro" ;;
        n) NUM="$OPTARG" ;;
        \?) usage ;;
    esac
done

shift $((OPTIND - 1))

if [ -z "$FORMAT" ]; then
    exit 1
fi

if [ "$#" -ne 2 ]; then
    exit 1
fi

ROSTER=$1
MARKS=$2

process_roster() {
    cut -d',' -f1,2,3 "$ROSTER" | sort -t, -k2,2
}

process_marks_markus() {
    sort -t, -k1,1 "$MARKS"
}

process_marks_ro() {
    sort -t, -k1,1 "$MARKS"
}

combine_and_process_markus() {
    join -t, -1 2 -2 1 -o 1.3,2.2 - "$MARKS" |
    sort -t, -k2,2nr | head -n "$NUM"
}

combine_and_process_ro() {
    join -t, -1 1 -2 1 -o 1.3,2.2 - "$MARKS" |
    sort -t, -k2,2nr | head -n "$NUM"
}

if [ "$FORMAT" = "markus" ]; then
    process_roster | combine_and_process_markus
elif [ "$FORMAT" = "ro" ]; then
    process_roster | sort -t, -k1,1 | combine_and_process_ro
fi
